Privacy a
usnistgov/800-63-3 pull request #1666
Opened 2017-04-27 18:19 UTC by jricher

2017-04-27 18:32 UTC, pgrassi-nist commented
Also closes #1143.  Missed the `#` sign in the commit above.

2017-05-02 01:47 UTC, jamiedanker-nppd approved these changes

2017-05-02 01:50 UTC, jamiedanker-nppd requested changes
See 4.3 - IAL is missing the 1. Put in a separate change (but don't know if I did this correctly :-)

2017-05-02 01:51 UTC, jamiedanker-nppd approved these changes

2017-05-02 01:53 UTC, jamiedanker-nppd approved these changes

2017-05-02 01:55 UTC, jamiedanker-nppd approved these changes

2017-05-02 01:56 UTC, jamiedanker-nppd approved these changes

2017-05-02 02:06 UTC, jamiedanker-nppd approved these changes
Changes all look good - wasn't sure if I needed to approve each individual commit.. only item that needs edit is to specify in 4.3 IAL1

2017-05-02 15:05 UTC, merged