Definitions Appendix Update!
usnistgov/800-63-3 pull request #1667
Opened 2017-04-28 17:04 UTC by pgrassi-nist

2017-04-28 20:28 UTC, jimfenton requested changes
The renumbering of the sections is very incomplete. If Section 3 is being removed, the section numbers in the following sections need to be changed and the references to section numbers elsewhere in the text need to be updated. It might also be worthwhile to change the names on the source files.

Alternatively, keep section 3 with a reference to the appendix, so that things don't need to be renumbered.

2017-05-01 17:49 UTC, pgrassi-nist commented
That's what I get for multitasking. Crud.  Yes, 3 is staying with a reference.  Standby

2017-05-01 17:59 UTC, pgrassi-nist commented
@jimfenton commit reverted.  This should be good, keeping numbering in tact.

2017-05-02 03:59 UTC, jimfenton approved these changes

2017-05-02 03:59 UTC, jimfenton commented on sp800-63c/sec3_definitions.md
> +See [800-63-3, Appendix A](https://pages.nist.gov/800-63-3/sp800-63-3.html#def-and-acr) for a complete set of definitions and abbreviations.
It can just say Appendix A because it's the same volume. I will push a fix.

2017-05-02 04:00 UTC, jimfenton commented on sp800-63c/sec3_definitions.md
> +See [800-63-3, Appendix A](https://pages.nist.gov/800-63-3/sp800-63-3.html#def-and-acr) for a complete set of definitions and abbreviations.
Oops, it's not. My mistake. But I will add the SP.

2017-05-02 15:45 UTC, merged