Reorganization of -C
usnistgov/800-63-3 pull request #1774
Opened 2017-05-16 21:46 UTC by jricher

2017-05-17 18:10 UTC, jimfenton requested changes
Also need to update README.md with new sections.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63-3/sec6_xAL.md
> +RPs should use a back-channel [presentation mechanism](sp800-63c.html#presentation) where possible, as such mechanisms allow for greater privacy and security. Since the subscriber handles only an ass
Cross-document references should be visible in printed text, i.e. this should look more like "presentation mechanism as described in SP 800-63C Section 7" with SP 800-63C Section 7 as the link text.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec11_examples.md
> +OpenID Connect [[OIDC]](#OIDC) is an internet-scale federated identity and authentication protocol built on top of the OAuth 2.0 authorization framework and the JSON Object Signing and Encryption (JO
Do we need to include the "As of this writing..." in the text? We don't do that elsewhere, and this is part of the reference.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/references.md
> +<a name="OIDC"><a>[OIDC] OpenID Foundation, *OpenID Connect Core 1.0*, available at: <http://openid.net/specs/openid-connect-core-1_0.html>.
If inclusion of errata through a particular date is relevant, include that too.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +All assertions SHALL comply with the detailed requirements in [Section 6](#assertions). While many other federation implementation options are possible, this list is intended to provide clear impleme
Does "this list" refer to the FALs or to the detailed requirements in Section 6?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +For example, FAL1 maps to the OpenID Connect Basic Client profile or SAML (Security Assertion Markup Language) Web SSO Artifact Binding profile, with no additional features. FAL2 additionally require
Suggest "FAL1 maps to, for example, the..."
Perhaps take the examples out of the second sentence: "FAL2 additionally requires that the assertion be..." since we're trying to state general requirements.
Suggest "FAL3 requires that the subscriber..." and delete "Note that" from the following sentence.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +If the RP is using a front-channel presentation mechanism as defined in [Section 7.2](#front-channel) (e.g., the OpenID Connect Implicit Client profile or the SAML Web SSO profile), it SHOULD require
"protect the information": even at FAL1, the assertion is signed, so you might want to say, "protect the information from disclosure". Is disclosure of assertions to the browser a significant threat?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +RPs MAY establish whitelists of IdPs that are authorized to send authentication and attributes to the RP, without runtime decision from the subscriber. RPs MAY also establish blacklists of IdPs who a
I'm confused about IdP and RP whitelists. In order not to require runtime decision from the subscriber, must the IdP and RP authorize each other? It seems dangerous for an RP to be able to say "it's OK to send attributes to me."
Has non-requirement for user consent been run by the privacy folks?
Should the blacklist statement say something like, "RPs MAY also establish lists of IdPs from which they will not accept authentication or attributes..." since they have little control over what is sent, only what they accept?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +The subscriber SHALL receive explicit notice and be able to provide positive confirmation before any attributes about the subscriber are transmitted to any RP. At a minimum, the notice SHOULD be prov
This seems to conflict with the whitelisting paragraphs (lines 43 and 45) as to whether user consent is required.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec6_assertions.md
> +Although details vary based on the exact federation protocol in use, an assertion SHOULD be used only to represent a single login event at the RP. After the RP consumes the assertion, [session manage
Include reference to -63B that is visible in printed text.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec6_assertions.md
> +#### <a name="ppi"></a> 5.3. Pairwise Pseudonymous Identifiers
6.3?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec7_presentation.md
>  ## 6. Assertion Presentation
7.?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec7_presentation.md
> +### <a name="back-channel"></a> 6.1. Back-channel Presentation
7.1?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec7_presentation.md
> +### <a name="front-channel"></a> 6.2. Front-channel Presentation
7.2?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec7_presentation.md
> +### <a name="protecting-information"></a> 6.3. Protecting Information
7.3?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec5_federation.md
> +The subscriber authenticates to the IdP as described in [[SP 800-63B]](sp800-63b.html), and then the result of that authentication event is asserted to the RP across the network. The IdP can also mak
-63B doesn't use the term IdP. Should this explain that this is the "verifier" referred to there?

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec5_federation.md
> +#### <a name="manual-registration"></a> 45.1.1. Manual Registration
5.1.1.

2017-05-17 18:10 UTC, jimfenton commented on sp800-63c/sec4_fal.md
> +#### 4.2. <a name="runtime-decisions"></a>Runtime Decisions
Wrong header level -- need to drop a '#'

2017-05-17 18:12 UTC, jricher commented on sp800-63c/sec11_examples.md
> +OpenID Connect [[OIDC]](#OIDC) is an internet-scale federated identity and authentication protocol built on top of the OAuth 2.0 authorization framework and the JSON Object Signing and Encryption (JO
Probably not anymore now that the reference is there.

2017-05-17 18:12 UTC, jricher commented on sp800-63-3/sec6_xAL.md
> +RPs should use a back-channel [presentation mechanism](sp800-63c.html#presentation) where possible, as such mechanisms allow for greater privacy and security. Since the subscriber handles only an ass
Didn't change existing link structures, just made sure they pointed to the right places.

2017-05-17 18:13 UTC, jricher commented on sp800-63c/sec4_fal.md
> +All assertions SHALL comply with the detailed requirements in [Section 6](#assertions). While many other federation implementation options are possible, this list is intended to provide clear impleme
the list of FALs themselves

2017-05-17 18:16 UTC, jricher commented on sp800-63c/sec4_fal.md
> +If the RP is using a front-channel presentation mechanism as defined in [Section 7.2](#front-channel) (e.g., the OpenID Connect Implicit Client profile or the SAML Web SSO profile), it SHOULD require
Protect it from disclosure (and subsequent leaking). Yes, it's significant, enough to warrant the requirement. Per another issues, this is a SHALL in another section (line was added by you) -- we need to make them parallel.

2017-05-17 18:17 UTC, jricher commented on sp800-63c/sec4_fal.md
> +#### 4.2. <a name="runtime-decisions"></a>Runtime Decisions
Good catch, this was promoted a level

2017-05-17 18:18 UTC, jricher commented on sp800-63c/sec4_fal.md
> +RPs MAY establish whitelists of IdPs that are authorized to send authentication and attributes to the RP, without runtime decision from the subscriber. RPs MAY also establish blacklists of IdPs who a
RP decisions are all about what they request and accept, not about what is sent. I can make the wording clearer.

2017-05-17 18:20 UTC, jricher commented on sp800-63c/sec4_fal.md
> +The subscriber SHALL receive explicit notice and be able to provide positive confirmation before any attributes about the subscriber are transmitted to any RP. At a minimum, the notice SHOULD be prov
This paragraph should apply only when a user-driven runtime decision is used. We want an IdP and RP to be able to whitelist each other for a smoother user experience, especially if we want to encourage federation technology internally (which we do).

2017-05-17 18:21 UTC, jricher commented on sp800-63c/sec7_presentation.md
>  ## 6. Assertion Presentation
Good catch, missed renumbering

2017-05-17 18:22 UTC, jricher commented on sp800-63c/sec5_federation.md
> +The subscriber authenticates to the IdP as described in [[SP 800-63B]](sp800-63b.html), and then the result of that authentication event is asserted to the RP across the network. The IdP can also mak
Good thought -- what we really want to say here is that the authentication process from the user to the IdP is covered entirely by B. Should be a simple matter of mapping terminology back. (We already map it forward in the intro)

2017-05-18 12:21 UTC, jricher commented
New change set should address all the issues here. See also #1776

2017-05-19 05:13 UTC, jimfenton approved these changes
Much better; thanks. I'll leave for you to merge because you're probably in a better position to resolve the merge conflict.

2017-05-22 04:40 UTC, jimfenton commented
I see that you're not actually in a better position to resolve the conflict, so I have done so and will do the merge after all.

2017-05-22 04:40 UTC, merged

2017-05-22 14:41 UTC, jricher commented
Should be good, the only real change in there was the reference anchor and some of the wording around session creation, which was kept. Thanks!