Missed a edits
usnistgov/800-63-3 pull request #1787
Opened 2017-05-24 18:58 UTC by pgrassi-nist

Sorry, caught some unassigned for -3 and wrapped them up.

2017-05-24 23:40 UTC, jimfenton requested changes
Very minor changes needed.

2017-05-24 23:40 UTC, jimfenton commented on sp800-63-3/sec1_2_introduction.md
> +adhere to the requirements of the *Federal Information Security Modernization Act* [[FISMA]](#FISMA), and related NIST standards and guidelines. FISMA directs Federal agencies to develop, document, a
Title III is also referenced in the definition of FISMA in the Definitions appendix.

2017-05-24 23:40 UTC, jimfenton commented on sp800-63-3/sec5_DIRM.md
> +Risk assessments determine the extent to which risk must be mitigated by the identity proofing, authentication, and federation processes. These determinations drive the relevant choices of applicable
Should include citation to SP 800-53.
nit: callout to section number doesn't have a trailing period: "Section 5.5." -> "Section 5.5"

2017-05-24 23:40 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +For example, item 1 can be satisfied by pairing a memorized secret (what you know) with an out-of-band-device (what you have). Both authenticator outputs are presented to the verifier to authenticate
nit: "out-of-band-device" -> "out-of-band device"

Possibly remove "in the authentication process" in last sentence. Seems redundant.

2017-05-25 02:59 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +adhere to the requirements of the *Federal Information Security Modernization Act* [[FISMA]](#FISMA), and related NIST standards and guidelines. FISMA directs Federal agencies to develop, document, a
I'm not seeing it in the current version of definitions.md

2017-05-25 03:03 UTC, pgrassi-nist commented on sp800-63-3/sec5_DIRM.md
> +Risk assessments determine the extent to which risk must be mitigated by the identity proofing, authentication, and federation processes. These determinations drive the relevant choices of applicable
5.5. has the trailing period but i added reference to 53

2017-05-25 04:44 UTC, jimfenton commented on sp800-63-3/sec1_2_introduction.md
> +adhere to the requirements of the *Federal Information Security Modernization Act* [[FISMA]](#FISMA), and related NIST standards and guidelines. FISMA directs Federal agencies to develop, document, a
My mistake; I was looking at nist-pages, not current version.

2017-05-25 04:50 UTC, jimfenton approved these changes

2017-05-25 04:50 UTC, merged