New graphics public comment
usnistgov/800-63-3 pull request #1789
Opened 2017-05-25 20:22 UTC by kboeckl

updated/new graphics, including decisions trees, icons, and more diagrams. closes #615, closes #1137, closes #811, and closes #1752.

2017-05-25 22:47 UTC, jricher requested changes
References to "attribute claims" need to be changed to "attribute references" instead (terminology change in text)

2017-05-26 01:56 UTC, pgrassi-nist commented
closes #1752, closes #615, closes #1193

2017-05-26 02:31 UTC, paul-grassi approved these changes

2017-05-26 12:18 UTC, jricher approved these changes

2017-05-26 14:18 UTC, merged