63C graphics
usnistgov/800-63-3 pull request #1790
Opened 2017-05-25 20:48 UTC by SarahSquire

2017-05-25 22:44 UTC, jricher approved these changes

2017-05-26 02:04 UTC, pgrassi-nist commented
closes #873
closes #811

2017-05-26 02:11 UTC, paul-grassi requested changes
We are missing the step-wise instructions for many of the graphics.  Any new ones with 1, 2, 2a...need descriptive text to go along with the graphics.

2017-05-28 04:51 UTC, paul-grassi approved these changes

2017-05-28 04:51 UTC, merged