A copy edit review - batch #1
usnistgov/800-63-3 pull request #1798
Opened 2017-05-26 22:24 UTC by RGalluzzo

Introduction General:
Switching between subject, subscriber, and claimant without clearly
aligning with the graphic. I did not change since it wasn’t clear which
was preferred. Suggest updating to be more consistent as part of the
next revision.
Section 1.2:
For example, in order to maintain integrity of the service, it may be
desirable to know the home ZIP Code of a user for purposes of census
taking or petitioning an elected official but where it is not necessary
or desirable to know the underlying identity of the person. – Awkward
example. Suggest shortening.
Section 2.2:
Real-live v. Real-world. They are used interchangeably. I changed all to
real-life for consistency.
The term validation is not used at all in IAL2 or IAL3. There is also no
discussion of evidence in either of these descriptions. Not sure if this
is intentional.
In the discussion of IAL 2&3 and anonymity there is the following
statement: “It may be beneficial to the user that uses a high assurance
CSP for transactions at lower assurance levels.  For example, a user may
maintain an IAL3 identity, yet should be able to use their CSP for IAL2
and IAL1 transactions.” This does not explain a benefit. I provided some
suggested re-wording.
Section 4:
We state that there is only one outcome of identity proofing here, but
in section one we list 4 outcomes. We should update and harmonize the
language in one of the two sections.
4.1.1.6 Address Confirmation
The term verified and validated seem to be used interchangeably with
regard to the address of record matching what is in records. I am not
sure if this is intentional or if one is preferred.
4.4.1.8 Security controls
Very confusing control. It says they shall have moderate or high and
then says they should have moderate.
Section 5
The table for identity evidence uses a wide array of terms for the
person being proofed – from applicant, to subject, to person, to
individual. I am not sure if this is intentional.

Left off at Table 5-2

2017-05-30 03:51 UTC, jimfenton requested changes
Good review; I have added my $0.02.

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec1_2_introduction.md
> +This document provides requirements for enrollment and identity proofing of subscribers that wish to gain access to resources at each Identity Assurance Level (IAL).  The requirements detail the acce
At the point that they're presenting their evidence, they're an applicant rather than a subscriber.

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec1_2_introduction.md
> +At IAL2 and IAL3, pseudonymity in federated environments is enabled by limiting the number of attributes sent from the CSP to the RP, or the way they are presented. For example, if a RP needs a valid
lower level --> lower-level
already verified --> already-verified
No comma after "noted", or perhaps just get rid of "It should be noted that"

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +The CSP may collect additional information in the process of identity proofing an applicant, provided validation and verification follow the requirements contained herein, and the applicant explicitl
may --> MAY (normative word)

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +	b. The CSP sends an enrollment code to the validated phone number of the applicant, the applicant provides the enrollment code to the CSP, and the CSP confirms they match, verifying the applicant is
verifying the applicant --> verifying that the applicant

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +4. The CSP SHALL NOT use attributes collected and maintained for the identity proofing process for any purpose other than identity proofing, authentication, attribute assertions, or to comply with la
attribute assertions --> attribute assertion

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +6. The identity proofing and enrollment processes SHALL be performed according to an applicable written policy or *practice statement* that specifies the particular steps taken to verify identities.
Add comma after i.e.
counter-measures --> countermeasures

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +	b. The PII, including any biometrics, images, scans, or other copies of the identity evidence that the CSP will maintain as a record of identity proofing. Note: Specific Federal, state, local, terri
AP style guide says federal is lowercase when used to distinguish from state, local, etc.

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +9. The entire identity proofing process, including transactions that involve a third party, SHALL occur over an Authenticated Protected Channel.
authenticated protected channel should not be capitalized.

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +10. <a name="gr13"></a>The CSP SHOULD obtain additional confidence in identity proofing using fraud mitigation measures, for example inspecting geolocation, examining the device characteristics of th
comma after e.g. (second instance)

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +The CSP SHALL employ appropriately tailored security controls, to include control enhancements, from the *moderate* or *high* baseline of security controls defined in [[SP 800-53]](#SP800-53) or equi
lowercase federal, I believe. http://writingexplained.org/ap-style/ap-style-federal

2017-05-30 03:51 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +The CSP SHALL employ appropriately tailored security controls, to include control enhancements, from the *high* baseline of security controls defined in [[SP 800-53]](#SP800-53) or an equivalent Fede
federal
e.g.,

2017-05-30 14:40 UTC, RGalluzzo commented
It seems my commits from today were added into this pull request. Some comments in addition to the new commits are included below:
Table 5-2
 “confirming the integrity of physical security features and *lack of fraudulent modification*.” This is an awkward statement. Suggest re-wording or dropping the “lack of” phrase.  A change could be “confirming the integrity of the physical security features and that the document is not fraudulent or inappropriately modified.”
5.3.2
4. Should this read “KBV SHOULD be based on *the issuing source or* multiple authoritative sources.”?
5. It seems difficult to move to from “should have multiple authoritative sources” to “should use micro-deposits” which don’t really leverage multiple authoritative sources. Perhaps flip 4 & 5 and go with something like “Where transactional history is not used, KBV should be based on multiple authoritative sources.”
6, a. Is this intended to read as if only one (1) of the questions needs to be a free form answer? 
5.3.3
Suggest changing “encounter” to “interaction” – encounter sounds unnecessarily aggressive. 
5.3.3.2
1. What qualifies as “departing?” Simply leaving field of view?
3. “The operator SHALL direct the applicant, as required, to remove any doubt in the proofing process.” Doubt in what? – Suggest rephrasing to “If the remote operator believes the applicant is attempting to fraudulently proof by leveraging means out of their field of view or that would otherwise compromise the validity of the identity proofing session they SHALL ask the applicant to show their surroundings to remove doubt or they SHALL immediately terminate the proofing session.”
5.3.4
4. Should “subscriber” actually be “trusted referee” here? Otherwise it’s not clear why this would be here.

2017-05-30 19:04 UTC, RGalluzzo commented
Yep. Messed that up! Either way, this is the final set of commits for this PR. Comments from the last review are below. Let me know if you have questions. 
Section 6
Use case #2. This just seems to be saying that “you want to get a credential.” I am not sure why this is considered “deriving.” It would seem like this should read something like: 
An applicant seeks to either add a new authenticator to an existing identity record or establish a new credential at a new CSP leveraging a previously created identity record. For example, if an applicant wants to switch CSPs and/or have another authenticator at a new CSP for other uses (e.g., basic browsing vs. financial). *This use case is covered by allowable identity evidence in [Section 5.2](#validate).*
Section 7
“The threats to the enrollment process include impersonation attacks and threats to the transport mechanisms for identity proofing, authenticator binding, and credential issuance. [Table 7-1](#63aSec7-Table1) lists the threats related to enrollment and identity proofing.” This seems to suggest there are more than just the two categories in the previous section. Are there actually three categories of threats: 1) Impersonation, 2) Intercept (mitm? Or something similar), 3) malfeasance of the infrastructure provider?
Denial of enrollment also doesn’t seem to fit neatly into impersonation either. Maybe the statement regarding categories is unnecessary?
Removed repetition of “during issuance” from the “issuance” attacks. Seemed redundant. Also—with these it seems like the examples overlap with MITM and “Duplication” from B. Is the new name for these solely because they are being placed in proofing? Or, do the examples need to be updated. For example:
Disclosure – an individual’s PII being submitted for proofing is collected by an attacker positioning themselves between the CSP and the applicant.
Tampering- An attacker modifies applicant information being submitted to the CSP during registration by positioning themselves between the CSP and applicant. 
Mitigation tables:
I am not sure I see much of a difference between the two social engineering examples.
Why combine Unauthorized issuance/social engineering, but not disclosure and tampering?
Section 8
8.1- I would suggest making reference to the benefits of reducing RP risk when discussing data minimization. The benefits as described now are somewhat vague. I am not sure how data minimization equates to more trust in the identity proofing process. 
8.1.1-“ Federal agencies need to review any decision to collect the SSN relative to their obligation to reduce the collection and unnecessary use of SSNs under Office of Management and Budget policy.” should probably quote the policy here. 
8.6- the use of authentication in this section seems inconsistent with the concept of a “digital identity guideline” rather than “electronic authentication guidelines.”

2017-05-31 00:02 UTC, jimfenton commented
Replaced by #1805

2017-05-31 00:02 UTC, closed without merging