clarified PPID generation
usnistgov/800-63-3 pull request #403
Opened 2016-09-28 17:28 UTC by jricher

2016-09-28 17:29 UTC, pgrassi-nist commented
@nbl-nist take a peek.

2016-09-28 19:01 UTC, nbl-nist commented
Let me know what you think of the following two sentences as a replacement for your newly edited sentence. I was trying to think from a potential assessor's point of view. Just to be clear, either construction places the burden for determining the validity of the correlation on the IdP. Is that where you want it? 

An IdP MAY generate the same identifier for a subscriber at multiple RPs at the request of those RPs, but only if those RPs have a demonstrable, pre-existing relationship that could justify an operational need for the correlation, such as a shared security domain or legal ownership. The RPs SHALL conduct a joint privacy risk assessment before requesting that the IdP generate the same identifier.

2016-09-28 19:21 UTC, jricher commented
How about instead of a "joint privacy risk assessment" (which sounds like a specific formal process), we have:

> The RPs SHALL consider the privacy risks associated with requesting a common identifier.

2016-09-28 19:23 UTC, nbl-nist commented
We’ve called for privacy risk assessments in other requirements. What’s the difference here?

From: Justin Richer <notifications@github.com>
Reply-To: usnistgov/800-63-3 <reply@reply.github.com>
Date: Wednesday, September 28, 2016 at 3:21 PM
To: usnistgov/800-63-3 <800-63-3@noreply.github.com>
Cc: "Lefkovitz, Naomi B. (Fed)" <naomi.lefkovitz@nist.gov>, Mention <mention@noreply.github.com>
Subject: Re: [usnistgov/800-63-3] clarified PPID generation (#403)


How about instead of a "joint privacy risk assessment" (which sounds like a specific formal process), we have:

The RPs SHALL consider the privacy risks associated with requesting a common identifier.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250271490>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ49BqClaejTWd-Kn4kT1NFrUZTfL_5Sks5qur4vgaJpZM4KJF-m>.

2016-09-28 19:36 UTC, jricher commented
@nbl-nist new text on the pull request, please review.

2016-09-28 19:37 UTC, jricher commented
Also: yes, it's up to the IdP to determine the validity of the correlation, always, since it's the IdP that is calculating the PPID.

2016-09-28 19:41 UTC, jricher commented
The difference is that it's a group of RPs together and that a joint privacy assessment may be unrealistic or unfeasible for a formal and documented process. 

The IdP MAY always reject a requested grouping, on any grounds.

2016-09-28 19:41 UTC, nbl-nist commented
I think the consent/request difference between the two sentences is jarring. Practically speaking, are there use cases where the IdP would initiate the generation and seek consent instead of responding to a request from RPs?

From: Justin Richer <notifications@github.com>
Reply-To: usnistgov/800-63-3 <reply@reply.github.com>
Date: Wednesday, September 28, 2016 at 3:36 PM
To: usnistgov/800-63-3 <800-63-3@noreply.github.com>
Cc: "Lefkovitz, Naomi B. (Fed)" <naomi.lefkovitz@nist.gov>, Mention <mention@noreply.github.com>
Subject: Re: [usnistgov/800-63-3] clarified PPID generation (#403)


@nbl-nist<https://github.com/nbl-nist> new text on the pull request, please review.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250276158>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ49BjHRKD09lD93cqrV4ob-0htDpU8gks5qusHGgaJpZM4KJF-m>.

2016-09-28 19:42 UTC, jricher commented
We need to capture that all RPs are OK with the correlation, not just that one of them requested it and claims to speak for the group, thus having both.

2016-09-28 19:56 UTC, nbl-nist commented
You could say “at the joint request.”

From: Justin Richer <notifications@github.com>
Reply-To: usnistgov/800-63-3 <reply@reply.github.com>
Date: Wednesday, September 28, 2016 at 3:42 PM
To: usnistgov/800-63-3 <800-63-3@noreply.github.com>
Cc: "Lefkovitz, Naomi B. (Fed)" <naomi.lefkovitz@nist.gov>, Mention <mention@noreply.github.com>
Subject: Re: [usnistgov/800-63-3] clarified PPID generation (#403)


We need to capture that all RPs are OK with the correlation, not just that one of them requested it and claims to speak for the group, thus having both.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250277787>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ49Bhe0NxWWO_IFGk7g9dE0XLnraPz-ks5qusM8gaJpZM4KJF-m>.

2016-09-28 19:56 UTC, nbl-nist commented
I’m not really seeing the issue, if they have the kind of operational relationship that we’re expecting. If they’re not that connected, what’s the point of limiting the exception? Anyway, the whole thing seems like hair-splitting since the previous section doesn’t have a blanket requirement to use PPIDs or at least a privacy risk assessment to justify under what circumstances PPIDs wouldn’t be used. I think this latter requirement should be added.

From: Justin Richer <notifications@github.com>
Reply-To: usnistgov/800-63-3 <reply@reply.github.com>
Date: Wednesday, September 28, 2016 at 3:41 PM
To: usnistgov/800-63-3 <800-63-3@noreply.github.com>
Cc: "Lefkovitz, Naomi B. (Fed)" <naomi.lefkovitz@nist.gov>, Mention <mention@noreply.github.com>
Subject: Re: [usnistgov/800-63-3] clarified PPID generation (#403)


The difference is that it's a group of RPs together and that a joint privacy assessment may be unrealistic or unfeasible for a formal and documented process.

The IdP MAY always reject a requested grouping, on any grounds.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250277481>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ49Bgo_yUtw3N1GM-iW7tnrkyTk2iKqks5qusL0gaJpZM4KJF-m>.

2016-09-28 20:11 UTC, jricher commented
Newest checkin re-added the risk assessment text, but kept the other text for appropriate context and motivation.

2016-09-29 00:34 UTC, jimfenton requested changes
Couple of mostly grammatical nits.

2016-09-29 00:34 UTC, jimfenton commented on sp800-63c/sec5_strength.md
> +The RPs SHALL conduct a privacy risk assessment to consider the privacy risks associated with requesting a common identifier. The IdP SHALL ensure that only intended RPs are correlated, otherwise a r
s/part that correlation/part of that correlation/

While you're at it, the comma after "correlated" should be a semicolon.

2016-09-29 00:34 UTC, jimfenton commented on sp800-63c/sec5_strength.md
> +* All RPs consent to being correlated in such a manner.
All RPs sharing the identifier? Or is the "sharing the identifier" part obvious?

2016-09-29 16:06 UTC, jimfenton approved these changes

2016-09-29 16:06 UTC, merged

2016-09-29 17:19 UTC, nbl-nist commented
Under the following language, the default is going to be to not use PPIDs because it's unclear under what circumstance it would be desirable and since the benefit accrues to the individual, who advocates for them? The default should be to use them, with exceptions allowed. 

In some circumstances, it is desirable to prevent the subscriber's account at the IdP from being linked through one or more RPs through use of a common identifier. In these circumstances, pairwise pseudonymous subject identifiers SHALL be used within the assertions generated by the IdP for the RP, and the IdP SHALL generate a different identifier for each RP.

2016-09-29 18:27 UTC, SarahSquire commented
Yeah, that's a valid concern. What if we replace "In some circumstances" with
"Unless there are mitigating factors"?

Sarah Squire
Engage Identity
http://engageidentity.com

On Thu, Sep 29, 2016 at 1:19 PM, nbl-nist <notifications@github.com> wrote:

> Under the following language, the default is going to be to not use PPIDs
> because it's unclear under what circumstance it would be desirable and
> since the benefit accrues to the individual, who advocates for them? The
> default should be to use them, with exceptions allowed.
>
> In some circumstances, it is desirable to prevent the subscriber's account
> at the IdP from being linked through one or more RPs through use of a
> common identifier. In these circumstances, pairwise pseudonymous subject
> identifiers SHALL be used within the assertions generated by the IdP for
> the RP, and the IdP SHALL generate a different identifier for each RP.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250532866>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL081Zu6v-sllH6BvfKuFzTrvc1q-kevks5qu_MsgaJpZM4KJF-m>
> .
>

2016-09-29 18:29 UTC, jricher commented
Or instead of "In some circumstances", we do "In many circumstances"?

2016-09-30 00:57 UTC, nbl-nist commented
I like it, but I still don’t know how to interpret “it is desirable.” Is that a SHOULD concept or a SHALL concept?
From: Sarah Squire <notifications@github.com>
Reply-To: usnistgov/800-63-3 <reply@reply.github.com>
Date: Thursday, September 29, 2016 at 2:27 PM
To: usnistgov/800-63-3 <800-63-3@noreply.github.com>
Cc: "Lefkovitz, Naomi B. (Fed)" <naomi.lefkovitz@nist.gov>, Mention <mention@noreply.github.com>
Subject: Re: [usnistgov/800-63-3] clarified PPID generation (#403)

Yeah, that's a valid concern. What if we replace "In some circumstances" with
"Unless there are mitigating factors"?

Sarah Squire
Engage Identity
http://engageidentity.com

On Thu, Sep 29, 2016 at 1:19 PM, nbl-nist <notifications@github.com> wrote:

> Under the following language, the default is going to be to not use PPIDs
> because it's unclear under what circumstance it would be desirable and
> since the benefit accrues to the individual, who advocates for them? The
> default should be to use them, with exceptions allowed.
>
> In some circumstances, it is desirable to prevent the subscriber's account
> at the IdP from being linked through one or more RPs through use of a
> common identifier. In these circumstances, pairwise pseudonymous subject
> identifiers SHALL be used within the assertions generated by the IdP for
> the RP, and the IdP SHALL generate a different identifier for each RP.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250532866>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL081Zu6v-sllH6BvfKuFzTrvc1q-kevks5qu_MsgaJpZM4KJF-m>
> .
>


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/usnistgov/800-63-3/pull/403#issuecomment-250551043>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ49BmQ2wMXFyWnrqjkv0nYhJpkkrgE4ks5qvAMUgaJpZM4KJF-m>.