Outbound plane to hk
usnistgov/800-63-3 pull request #408
Opened 2016-10-03 01:21 UTC by pgrassi-nist

2016-10-03 17:00 UTC, jimfenton commented
Commit 3ff94f5 changes the line terminators on 800-63b/sec10_usability.md. Some lines already had terminator issues, but there are more now.

2016-10-03 17:10 UTC, jimfenton requested changes
It's very hard to review the sections where the line terminators changed because everything shows up as a difference. Let me know if you have a way to clean those up or would like me to do so.

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +2.	The CSP SHALL collect biometrics in such a way that ensures that the biometric is collected from the applicant, and not another individual. All biometric requirements in [SP 800-63B, Section 5.2.3
Suggest using "biometric performance requirements", as this biometric is not used with another factor. Or perhaps we should break -63B 5.2.3 into two parts.

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +It is possible for a CSP to achieve the security and confidence comparable to in-peson proofing over remote channels.  The following requirements establish comparability between in-person transaction
locatin -> location

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +4. The CSP SHALL provide that all digital verification of evidence (e.g., via chip or wireless technologies) is performed by scanners and sensors that are integrated into the solution and in the enti
Suggest provide -> require. is -> be

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +8. The CSP SHALL ensure all communications take place over a mutually authenticated encrypted session.
Suggest "ensure" -> "ensure that"
Should it say, "all communications with the kiosk"?

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +4. The CSP SHALL provide that all digital verification of evidence (e.g., via chip or wireless technologies) is performed by scanners and sensors that are integrated into the solution and in the enti
Also suggest solution -> kiosk because that's what we call it elsewhere.

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +2. 2.	The CSP SHALL require all actions taken by the applicant during the enrollment and identity proofing process to an operator. are clearly visible and without doubt.
Stray period? Suggest "The CSP SHALL require all actions taken by the applicant during the enrollment and identity proofing process to be clearly visible to the remote operator. The operator SHALL direct the applicant as required to remove any doubt in the proofing process."

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +The CSP MAY use trusted referees, such as notaries, legal guardians, medical professionals, conservators, persons with power attorney, or some other form of certified/approved individuals that can vo
"power attorney" -> "power of attorney"

2016-10-03 17:10 UTC, jimfenton commented on sp800-63a/sec4_ial.md
> +<a name="sec4"></a>
I don't know what happened here, but this commit changed all of the line terminators in the file from NL (Unix standard) to CR NL (DOS standard), which is why the diff looks funny. We should try to keep the line terminators as consistent as possible. I'm guessing that this is coming from your loaner laptop. I can push a commit to clean that up if you want.

2016-10-03 17:34 UTC, jimfenton commented on sp800-63a/sec3_definitions.md
> -#### Unverified Name
Should "Verified name" also have been deleted? It's not used.

2016-10-04 01:40 UTC, pgrassi-nist commented on sp800-63a/sec5_proofing.md
> +2.	The CSP SHALL collect biometrics in such a way that ensures that the biometric is collected from the applicant, and not another individual. All biometric requirements in [SP 800-63B, Section 5.2.3
fixed.  May be a good idea to break up though.

2016-10-04 01:45 UTC, pgrassi-nist commented on sp800-63a/sec5_proofing.md
> +4. The CSP SHALL provide that all digital verification of evidence (e.g., via chip or wireless technologies) is performed by scanners and sensors that are integrated into the solution and in the enti
Fixed, but I am not sure I want to go with kiosk as that is a 'for example'.  But I'm happy to move away from 'solution'.

2016-10-04 01:52 UTC, pgrassi-nist commented
Thanks @jimfenton.  I think no more editing on a plane :)

Also, terminator issues have to be due to laptop and editor.  I think I won't edit the doc any more this week.

2016-10-04 01:53 UTC, pgrassi-nist commented on sp800-63a/sec3_definitions.md
> -#### Unverified Name
done.  I was trying just to fix dberigni issues, but knocked this one out too.

2016-10-04 02:03 UTC, jimfenton commented
Don't let this get in the way of being productive. Now that I know this is happening, I'll just watch for non-standard terminators and commit changes to fix that.

In case you aren't aware, by default GitHub lets people with write access to the repo you're sending a pull request to commit changes to your branch prior to the merge. I can do that with the existing line terminator issues if that's OK with you.

2016-10-04 02:05 UTC, pgrassi-nist commented
Sounds good to me. Thanks.

2016-10-04 03:46 UTC, jimfenton approved these changes

2016-10-04 03:46 UTC, merged