Address Elaine  Barker's -A issues.
usnistgov/800-63-3 pull request #412
Opened 2016-10-06 02:43 UTC by pgrassi-nist

2016-10-06 06:39 UTC, jimfenton requested changes

2016-10-06 06:39 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +- The CSP SHOULD perform KBV by verifying knowledge of recent transactional history that the CSP is a participant to.  The CSP SHALL ensure transaction information meets the minimum entropy for a Mem
"participant to" -> "participant in"
"ensure" -> "ensure that"
Memorized secrets don't have any explicit entropy requirements. However, in most other places, we require 20 bits of entropy (OTP authenticator) outputs, for example) so maybe just say "20 bits of entropy" here.
The sentence starting "For example," needs a verb.
"questions of the claimed identity" -> "questions of the claimant"

2016-10-06 06:39 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +	- The CSP SHALL NOT use data in KBV questions that does not change regularly over a period of time.
The data isn't in the KBV questions, so:
"The CSP SHALL NOT use KBV questions whose answers do not change regularly over a period of time."

2016-10-06 06:39 UTC, jimfenton commented on sp800-63a/sec6_dc.md
> +6. The derived authenticator SHALL be issued at or below the primary authenticator IAL. For example, if the primary IAL is 2, the authenticator that is issued could be AAL2 or 1.
This really confuses me. Why couldn't you have an AAL 3 authenticator at IAL 2? It's the converse that's the problem: you can't have an AAL 1 authenticator at IAL 2.

2016-10-06 06:39 UTC, jimfenton commented on sp800-63a/sec6_dc.md
> +8. A new authenticator SHALL be issued at or below the primary authenticator IAL. For example, if the primary IAL is 2, the authenticator that is issued could be AAL2 or 1.
See above.

2016-10-11 15:47 UTC, paul-grassi commented on sp800-63a/sec5_proofing.md
> +- The CSP SHOULD perform KBV by verifying knowledge of recent transactional history that the CSP is a participant to.  The CSP SHALL ensure transaction information meets the minimum entropy for a Mem
will fix, need to load up foreign travel laptop since the commit is there :(

2016-10-11 15:47 UTC, pgrassi-nist commented on sp800-63a/sec5_proofing.md
> +	- The CSP SHALL NOT use data in KBV questions that does not change regularly over a period of time.
good catch

2016-10-11 15:49 UTC, pgrassi-nist commented on sp800-63a/sec6_dc.md
> +6. The derived authenticator SHALL be issued at or below the primary authenticator IAL. For example, if the primary IAL is 2, the authenticator that is issued could be AAL2 or 1.
because derived credentials are all about the proofing.  but boy did we potentially throw a wrench in that.  We should discuss today.

2016-10-11 16:04 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +- The CSP SHOULD perform KBV by verifying knowledge of recent transactional history that the CSP is a participant to.  The CSP SHALL ensure transaction information meets the minimum entropy for a Mem
You should be able to just fetch the changes from your GitHub repository into your usual laptop; it's all there.

2016-10-11 21:18 UTC, pgrassi-nist commented
@jimfenton that should do it.  It's not pretty, but I think it gets us there.  Keep in mind, we will have an operational guide, informative supplement, to -63 where we can deep dive into this.  I also think we can have more intro text if you think that would help.  This is new stuff, so it wouldn't hurt.  If you think that works, I can add a new commit before we merge.

2016-10-12 04:32 UTC, jimfenton approved these changes

2016-10-12 04:43 UTC, merged