800-53-3 editorial changes
usnistgov/800-63-3 pull request #413
Opened 2016-10-07 05:36 UTC by jimfenton

These are the (hopefully) small and non-controversial changes. I have some other changes that we should discuss before making.

2016-10-11 15:35 UTC, paul-grassi requested changes

2016-10-11 15:35 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +* FAL refers to the robustness of the assertion protocol utilized by the federation to communicate authentication and attribute information (if applicable) to a separate relying party.
separate from what?  I know IdP, but if the inferred separation (as originally written) isn't good form, then we should be clear when adding 'separate'.

2016-10-11 15:35 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**Authenticator Assurance Level 1** - AAL 1 provides single factor authentication, giving some assurance that the same claimant who participated in previous transactions is accessing the protected tr
For AAL1-3, this doesn't look like the new language you added per Bill's comments.

2016-10-11 15:35 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**Federation Assurance Level 1** - FAL 1 allows for the subscriber to retrieve and present a bearer assertion directly to the relying party (RP) in the front channel. The assertion must be asymmetric
Don't worry about it, but this is the stuff we will fix later.

2016-10-11 15:35 UTC, pgrassi-nist commented on sp800-63-3/sec4_model.md
> +As part of authentication, mechanisms such as device identity or geo-location may be used to identify or prevent possible authentication false positives. While these mechanisms do not directly increa
I see 'may'.  Do we need the hassle of cleaning out 'normative' words or is stating these sections (actually all of -3) is informative enough?  I hope the latter :)

2016-10-11 16:11 UTC, jimfenton commented on sp800-63-3/cover.md
> +* FAL refers to the robustness of the assertion protocol utilized by the federation to communicate authentication and attribute information (if applicable) to a separate relying party.
Maybe, "...to a relying party that is separate from the federation" ?

2016-10-11 16:20 UTC, paul-grassi commented on sp800-63-3/cover.md
> +* FAL refers to the robustness of the assertion protocol utilized by the federation to communicate authentication and attribute information (if applicable) to a separate relying party.
I don't know why we need 'separate' since we are already talking about a federation.  What about 'to an RP participating in the federation'.

2016-10-11 16:36 UTC, jimfenton commented on sp800-63-3/cover.md
> +* FAL refers to the robustness of the assertion protocol utilized by the federation to communicate authentication and attribute information (if applicable) to a separate relying party.
Let's just drop the word then. I'm not sure that I'd say that RPs participate in federations; they rely on them but unless you're referring to signals they aren't active participants. I will change.

2016-10-11 16:54 UTC, jimfenton commented on sp800-63-3/cover.md
> +**Authenticator Assurance Level 1** - AAL 1 provides single factor authentication, giving some assurance that the same claimant who participated in previous transactions is accessing the protected tr
Good catch. I didn't apply those changes to the introduction and executive summary in -63B, so when I cut and pasted the text here, it didn't get picked up. Look for another commit to fix this and a pull request to make -63B self-consistent.

2016-10-11 19:32 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +As part of authentication, mechanisms such as device identity or geo-location may be used to identify or prevent possible authentication false positives. While these mechanisms do not directly increa
I hope the latter too.

2016-10-13 00:49 UTC, paul-grassi approved these changes

2016-10-13 00:49 UTC, merged