adding graphic placeholders for CYOA.
usnistgov/800-63-3 pull request #421
Opened 2016-10-21 15:31 UTC by pgrassi-nist

2016-10-21 17:44 UTC, jimfenton requested changes
I notice the two new graphics aren't referenced anywhere. I gather these are just placeholders for now?

2016-10-21 17:44 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to collect from the applicant the most appropriate identity evidence (for example, a passport or drivers license) and determine its authenticity, validity, and accu
Isn't that three process steps now?

I'd suggest using a verb other than "confirming" multiple times. Perhaps "validating the evidence" and "verifying the data..." to be consistent with GPG 45 terminology?

2016-10-21 17:44 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to confirm and establish a linkage between the claimed identity to the to the physical, live existence of the person actually presenting the evidence.
s/to the to the/and the/

2016-10-21 18:00 UTC, paul-grassi commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to collect from the applicant the most appropriate identity evidence (for example, a passport or drivers license) and determine its authenticity, validity, and accu
validation is not verification (linking it to the person presenting it).  Maybe: determining that the evidence is genuine and authentic, and confirming the data contained on the identity evidence is valid, current, and related to an actual, live individual.

I munge this as 2 steps.  Collect, then do all the validation.  Happy to make it 3.

2016-10-21 18:00 UTC, paul-grassi commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to confirm and establish a linkage between the claimed identity to the to the physical, live existence of the person actually presenting the evidence.
good catch.  Can you fix that directly?

2016-10-21 18:01 UTC, paul-grassi commented
Yup, graphics are just a placeholder.

2016-10-21 18:40 UTC, jimfenton commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to confirm and establish a linkage between the claimed identity to the to the physical, live existence of the person actually presenting the evidence.
Sure. Do you want me to do anything with the other comment?

2016-10-23 18:30 UTC, pgrassi-nist commented on sp800-63a/sec5_proofing.md
> +The goal of identity validation is to confirm and establish a linkage between the claimed identity to the to the physical, live existence of the person actually presenting the evidence.
@jimfenton this looks really good.  It came across weird in email, hence my initial response, but online it looks great!

2016-10-23 18:31 UTC, pgrassi-nist commented
Sorry about the confusion.  It was the way GH put things in email.  I am good with your edits.  Please merge if you are ok.

2016-10-24 00:43 UTC, jimfenton approved these changes

2016-10-24 00:43 UTC, merged