Minor edits to assertion presentation based on discussion with Naomi …
usnistgov/800-63-3 pull request #424
Opened 2016-10-26 16:30 UTC by pgrassi-nist

…and Jamie.

2016-10-26 22:12 UTC, jricher requested changes

2016-10-26 22:12 UTC, jricher commented on sp800-63c/sec6_presentation.md
> +To mitigate the risk of unauthorized exposure of sensitive information (e.g., shoulder surfing), the CSP SHALL, by default, mask sensitive information displayed to the subscriber.  The CSP SHALL prov
We don't have a definition of what it means to "mask" information. For example, we should allow the CSP to "mask" by not displaying the information in the first place, and the current language choice sounds like it's only black-out.

2016-10-27 12:56 UTC, pgrassi-nist commented on sp800-63c/sec6_presentation.md
> +To mitigate the risk of unauthorized exposure of sensitive information (e.g., shoulder surfing), the CSP SHALL, by default, mask sensitive information displayed to the subscriber.  The CSP SHALL prov
I'll add something. We also have the UX chapter coming, that will have more language about masking.

2016-10-27 15:53 UTC, jricher approved these changes

2016-10-27 15:53 UTC, merged