Remove assertion requirements from 800-63B, since they are covered in…
usnistgov/800-63-3 pull request #448
Opened 2016-11-25 23:16 UTC by jimfenton

… 800-63C.

Avoided use of "assertion" in some contexts where distinction from -63C assertions may not be clear.

2016-11-25 23:17 UTC, jimfenton commented
@jricher It looks like you just updated section 7.2.3, so I assumed it's still current but please double-check.

2016-11-28 18:41 UTC, jricher requested changes
Needs one typo fixed but otherwise it's good.

2016-11-28 18:41 UTC, jricher commented on sp800-63b/sec7_session.md
> +To facilitate this behavior, a *session* MAY be started in response to an authentication event, and such a session SHALL continue until such time that it is terminated. The session MAY be terminated
Typo: "establishing"

2016-11-28 18:42 UTC, jricher commented
Actually one more change: the table in 4.5 also needs to be updated to remove the assertion reference.

2016-11-28 19:11 UTC, jricher approved these changes

2016-11-28 19:12 UTC, merged