Mike 3 edits
usnistgov/800-63-3 pull request #467
Opened 2016-12-23 16:14 UTC by pgrassi-nist

@garciamike we discussed most 'controversial' comments yesterday.  All that is left is a check of the executive summary. @jimfenton go for a full review since I messed up your ability to see Mike's original PR.  I have allowed for both of you to make edits to these commits, but if you prefer I do, just add a comment and I'll get to it.  Happy Holidays!!

@jimfenton the derived credential PR is next :)

2016-12-23 22:06 UTC, jimfenton requested changes
Some purely editorial changes that I could make, but also some questions about new wording that I'd like to get comment from @garciamike on.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +These guidelines provide technical requirements for Federal agencies
With this wording change, following line should read, "and are not intended". The following sentence refers to "the recommendation covers..." which should now say, "The guidelines cover...". The following sentence should begin, "They define..." and remove "for each".

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +The terms “CAN” and “CANNOT” indicate a possibility and capability, whether material, physical or causal or, in the negative, the absense of that possibility or capability.
absense -> absence

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +Digital identity is the online persona of a subject, and a single definition is widely debated internationally. Persona is apropos as a subject can represent themself online in many ways. An individu
While "subject" is a correct term of art, the scope of 800-63 is authentication of people, so more personal words like "individual" or "user" are more specific and less jargony IMO. Also note that the wording seems to be jumping between "subject" and "individual".

"can be someone streaming music server" doesn't parse. Is it "someone's streaming music server" (which might be out of scope because it's a server, not a person) or "someone streaming music" (which would be in scope)?

Dogs are out of scope too :). But any identity proofing process should be sufficient to detect dogs, so Steiner's cartoon hopefully doesn't apply. The actual caption on Steiner's cartoon (according to my New Yorker coffee cup) is, "On the Internet, nobody knows you're a dog." (Oh, looks like that's correct in the References)

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +For these guidelines, digital identity is the unique representation of a subject engaged in an online transaction. A digital identity is always unique in the context of a digital service, but does no
"does not need to uniquely identify": suggest "does not necessarily need to uniquely identify" because of course there are cases where one does need to uniquely identify the subject.

Wonder if "risk-based assurances" implies use of risk-based authentication techniques (things like IP geolocation) which aren't discussed in the document.

The two sentences beginning with "Digital authentication is..." seem somewhat redundant. Suggest "Digital authentication establishes that a subject attempting to access a digital service is in control of one or more valid authenticators associated with that subject's digital identity."

Last sentence beginning "Of which" has somewhat quirky wording.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +These guidelines do not view LOA in the context of a single ordinal that drive all implementation specific requirements.  Rather, by combining appropriate business and privacy risk management side-by
drive -> drives

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +NIST SP 800-63-A addresses how applicants can prove their identities and become enrolled as valid subjects within an identity system. It provides guidelines for processes by which applicants can both
subjects -> subscribers

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +**IAL 2**: Evidence supports the real-world existence of the claimed identity and verifies that the applicant is appropriately associated with this real-world identity.  IAL 2 introduces the need for
Just noticed that CSP isn't defined until the 800-63B paragraph below. Should be defined earlier. RP too.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +**AAL 1**: Provides some assurance that the claimant controls the authenticator registered to a subscriber. AAL 1 requires at least single-factor authentication using a wide range of available authen
"at least single factor": The requirement at AAL 1 is for one authenticator; saying "at least" here blurs what the actual requirement is.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +**AAL 2**: Provides high confidence that the claimant controls the authenticators registered to a subscriber. In addition to requirements of AAL 1, two different authentication factors are required.
"controls the authenticators" -> "controls authenticators" since there may be more authenticators associated with the identity than are actually used to authenticate (backup authenticators, mobile devices, etc.)

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +**AAL 3** – Provides very high confidence that the claimant controls the authenticator registered to a subscriber. In addition to requirments for AAL 2, authentication at AAL 3 is based on proof of p
"controls the authenticator" -> "controls authenticators"

Last sentence implies that all hard crypto authenticators provide [verifier] impersonation resistance, which isn't accurate. Suggest 'requires a "hard" cryptographic authenticator that provides verifier impersonation resistance.'

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/cover.md
> +**FAL 1**: Allows for the subscriber to enable the relying party (RP) to receive a bearer assertion. The assertion is signed by the IdP using approved cryptography.
IdP -> Identity Provider (IdP)

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec3_definitions.md
> +*This section is informative.*
Needed? The entire document is informative.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec1_2_introduction.md
> +These guidelines do not view LOA in the context of a single ordinal that drive all implementation specific requirements.  Rather, by combining appropriate risk management for business, security, and
"ordinal that drive" -> "ordinal that drives"

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec1_2_introduction.md
> +* **IAL** refers to the identity proofing process and the binding between one or more authenticators and the records pertaining to a specific claimant.
claimant -> applicant

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec1_2_introduction.md
> +The business model, marketplace, and the composition of the way identity services are delivered has drastically changed since first version of Special Publication 800-63 was released.  Notably, CSPs
"since first version" -> "since the first version"

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec3_definitions.md
> +In the context of [[OMB M-04-04]](#M-04-04) and this document, assurance is defined as 1) the degree of confidence in the vetting process used to establish the identity of a claimant to whom a creden
claimant -> applicant (first occurrence)

"same as that" -> "same as the subscriber"

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec3_definitions.md
> +The process of identifying, estimating, and prioritizing risks to organizational operations (including mission, functions, image, reputation), organizational assets, individuals, other organizations,
Need conjunctions: "or reputation", "and other organizations".

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec3_definitions.md
> +A person, organization, device, hardware, network, software, or service.
In the context of this document, isn't a subject constrained to be a person?

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +The process used to verify an applicant's association with their real world identity is called *identity proofing*. The strength of identity proofing is described by an ordinal measurement called the
"CSP may also assert": in addition to what? Identifier(s), or identifying attributes? (or leave out the "also")

Need conjunction (perhaps and/or) between attribute claims, pseudonymous identifiers.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +Multi-factor authentication refers to the use of more than one of the factors listed above. The strength of authentication systems is largely determined by the number of factors incorporated by the s
(in the old version also): I'm not sure we should include the three-factors stuff; it's not clear how much stronger three-factor is than two-factor (may not be much depending on the threat model), and it begs the question of why we don't have an AAL requiring three factors.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +In this document, authenticators always contain a secret. Some of the classic authentication factors do not apply directly to digital authentication. For example, an ID badge is something you have, a
"as part of a multifactor authenticator" differs subtly from current requirements. Better wording would be "when strongly bound to a physical authenticator".

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec4_model.md
> +However, this guideline does recognize that authentication systems that incorporate all three factors offer better security than systems that incorporate two of the factors. A digital authentication
Again, we don't really make the point that three factors are better. This wording might be slightly off since we have allowed, in very limited circumstances, the central verification of biometrics.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +However, in today's digital services, combining proofing and authenticator requirements into a single bundle sometimes has unintended consequences and can put unnecessary implementation burden upon t
are not rightfully -> is not rightfully

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +| **AAL2** – AAL 2 provides high confidence that the claimant controls authenticator(s) registered to a subscriber. Proof of possession and control of two different authentication factors are require
are required -> is required
autheticatoni -> authentication

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +> Note: LOA2 requirements are now equivalent to LOA3.
Insert space between LOA and digit. Need to do that for the ALs as well.

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +| **IAL1** - At this level, attributes, if any, are self-asserted or should be treated as self-asserted.|
IAL1 -> IAL 1 (and add space in following 2 lines)

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +|**AAL1** - AAL 1 provides some assurance that the claimant controls an authenticator registered to a subscriber. AAL 1 uses single-factor authentication using a wide range of available authenticatio
AAL1 -> AAL 1 (and add space in following two lines)

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +> Note: Per Executive Order 13681 [[EO 13681]](#EO13681), the release of personal data requires protection with multifactor authentication, even if the personal data is self-asserted and not validate
Spaces between AL and digit

2016-12-23 22:06 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
>  | **IAL2** |  **NO** | Allowed | Allowed |
Spaces between AL and digit in table

2016-12-24 20:54 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +These guidelines provide technical requirements for Federal agencies
Fixed

2016-12-24 20:54 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +The terms “CAN” and “CANNOT” indicate a possibility and capability, whether material, physical or causal or, in the negative, the absense of that possibility or capability.
fixed

2016-12-24 20:55 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +Digital identity is the online persona of a subject, and a single definition is widely debated internationally. Persona is apropos as a subject can represent themself online in many ways. An individu
fixed

2016-12-24 20:58 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +For these guidelines, digital identity is the unique representation of a subject engaged in an online transaction. A digital identity is always unique in the context of a digital service, but does no
fixed

2016-12-24 21:00 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +These guidelines do not view LOA in the context of a single ordinal that drive all implementation specific requirements.  Rather, by combining appropriate business and privacy risk management side-by
fixed

2016-12-24 21:00 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +NIST SP 800-63-A addresses how applicants can prove their identities and become enrolled as valid subjects within an identity system. It provides guidelines for processes by which applicants can both
fixed - i was trying not to get too in the weeds on the valid terms for each volume, but i see the point.

2016-12-24 21:02 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**IAL 2**: Evidence supports the real-world existence of the claimed identity and verifies that the applicant is appropriately associated with this real-world identity.  IAL 2 introduces the need for
I'm ok with this.  I think we  may add too much noise if we started to define everything here.  Section 4 gets into the weed.

2016-12-24 21:02 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**AAL 1**: Provides some assurance that the claimant controls the authenticator registered to a subscriber. AAL 1 requires at least single-factor authentication using a wide range of available authen
Maybe, but we state elsewhere MFA is always preferred, so I actually like this change.

2016-12-24 21:03 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**AAL 2**: Provides high confidence that the claimant controls the authenticators registered to a subscriber. In addition to requirements of AAL 1, two different authentication factors are required.
fixed.

2016-12-24 21:03 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**AAL 3** – Provides very high confidence that the claimant controls the authenticator registered to a subscriber. In addition to requirments for AAL 2, authentication at AAL 3 is based on proof of p
fixed.

2016-12-24 21:04 UTC, pgrassi-nist commented on sp800-63-3/cover.md
> +**FAL 1**: Allows for the subscriber to enable the relying party (RP) to receive a bearer assertion. The assertion is signed by the IdP using approved cryptography.
fixed.

2016-12-24 21:04 UTC, pgrassi-nist commented on sp800-63-3/sec3_definitions.md
> +*This section is informative.*
good question.  We need to discuss.  Leaving for now.

2016-12-24 21:05 UTC, pgrassi-nist commented on sp800-63-3/sec3_definitions.md
> +In the context of [[OMB M-04-04]](#M-04-04) and this document, assurance is defined as 1) the degree of confidence in the vetting process used to establish the identity of a claimant to whom a creden
fixed

2016-12-24 21:06 UTC, pgrassi-nist commented on sp800-63-3/sec3_definitions.md
> +The process of identifying, estimating, and prioritizing risks to organizational operations (including mission, functions, image, reputation), organizational assets, individuals, other organizations,
fixed.

2016-12-24 21:07 UTC, pgrassi-nist commented on sp800-63-3/sec3_definitions.md
> +A person, organization, device, hardware, network, software, or service.
as discussed leaving room for NPE someday.

2016-12-24 21:08 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +These guidelines do not view LOA in the context of a single ordinal that drive all implementation specific requirements.  Rather, by combining appropriate risk management for business, security, and
fixed

2016-12-24 21:08 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +* **IAL** refers to the identity proofing process and the binding between one or more authenticators and the records pertaining to a specific claimant.
actually made it subscriber.

2016-12-24 21:09 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +The business model, marketplace, and the composition of the way identity services are delivered has drastically changed since first version of Special Publication 800-63 was released.  Notably, CSPs
fixed

2016-12-24 21:13 UTC, pgrassi-nist commented on sp800-63-3/sec4_model.md
> +The process used to verify an applicant's association with their real world identity is called *identity proofing*. The strength of identity proofing is described by an ordinal measurement called the
fixed.

2016-12-24 21:14 UTC, pgrassi-nist commented on sp800-63-3/sec4_model.md
> +Multi-factor authentication refers to the use of more than one of the factors listed above. The strength of authentication systems is largely determined by the number of factors incorporated by the s
All for it.  Fixed.

2016-12-24 21:15 UTC, pgrassi-nist commented on sp800-63-3/sec4_model.md
> +In this document, authenticators always contain a secret. Some of the classic authentication factors do not apply directly to digital authentication. For example, an ID badge is something you have, a
fixed

2016-12-24 21:17 UTC, pgrassi-nist commented on sp800-63-3/sec4_model.md
> +However, this guideline does recognize that authentication systems that incorporate all three factors offer better security than systems that incorporate two of the factors. A digital authentication
fixed, i think

2016-12-24 21:21 UTC, pgrassi-nist commented on sp800-63-3/sec5_xAL.md
> +However, in today's digital services, combining proofing and authenticator requirements into a single bundle sometimes has unintended consequences and can put unnecessary implementation burden upon t
fixed

2016-12-24 21:23 UTC, pgrassi-nist commented on sp800-63-3/sec5_xAL.md
> +| **IAL1** - At this level, attributes, if any, are self-asserted or should be treated as self-asserted.|
not sure what you mean with spaces.

2016-12-24 21:34 UTC, pgrassi-nist commented on sp800-63-3/sec5_xAL.md
> +|**AAL1** - AAL 1 provides some assurance that the claimant controls an authenticator registered to a subscriber. AAL 1 uses single-factor authentication using a wide range of available authenticatio
same.  I think we are going to standardize on no space between xAL and #.  Deloitte can do that.

2016-12-24 21:35 UTC, pgrassi-nist commented on sp800-63-3/sec5_xAL.md
> +| **AAL2** – AAL 2 provides high confidence that the claimant controls authenticator(s) registered to a subscriber. Proof of possession and control of two different authentication factors are require
fixed

2016-12-24 21:35 UTC, pgrassi-nist commented on sp800-63-3/sec5_xAL.md
> +> Note: LOA2 requirements are now equivalent to LOA3.
see prior.  I forgot if we made a decision :)

2016-12-24 22:16 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +> Note: LOA2 requirements are now equivalent to LOA3.
Mike expressed a slight preference for the space so that was enough to push me that direction.

2016-12-24 22:17 UTC, jimfenton commented on sp800-63-3/cover.md
> +**AAL 3** – Provides very high confidence that the claimant controls the authenticator registered to a subscriber. In addition to requirments for AAL 2, authentication at AAL 3 is based on proof of p
Only one "requires" here.

2016-12-24 23:50 UTC, jimfenton commented on sp800-63-3/sec5_xAL.md
> +| **IAL1** - At this level, attributes, if any, are self-asserted or should be treated as self-asserted.|
I meant that the other occurrences also need to change (IAL2 to IAL 2 and IAL3 to IAL 3)

2016-12-28 23:52 UTC, jimfenton approved these changes
Looks ready to merge now. Most of the remaining inconsistencies, like spaces between xAL and the digit, are better handled separately. Couple of other very minor things spotted.

I'd recommend merging this pull before pulling Mike's next changes into the mike-3-edits branch. That way, we won't have quite as much "in the air", being changed, at once.

2016-12-28 23:52 UTC, jimfenton commented on sp800-63-3/cover.md
> +Digital identity is the online persona of a subject, and a single definition is widely debated internationally. Persona is apropos as a subject can represent themself online in many ways. An individu
Second sentence start: suggest "The term *persona*..."

"Digital identity as a legal identity" -> "Digital identity as a legal entity"

2016-12-28 23:52 UTC, jimfenton commented on sp800-63-3/sec3_definitions.md
> +A meaningless but unique number that does not allow the RP to infer the subscriber but which does permit the RP to associate multiple interactions with the subscriber’s claimed identity.
Maybe "infer anything regarding the subscriber" rather than "infer the subscriber"

2016-12-29 19:46 UTC, merged