Copy-edit pull request
usnistgov/800-63-3 pull request #487
Opened 2017-01-20 20:55 UTC by rajdinh

Copy-edit done based on list of priorities sent over - so first acronym use, consistency in lists, headers, spacing and more. Additional comments (mostly about a few references) have also been emailed.

2017-01-20 20:57 UTC, rajdinh commented
Please note this copy-edit is ONLY for the 800-63-3 document and does not include A, B, or C.

2017-01-20 21:40 UTC, paul-grassi requested changes

2017-01-20 21:40 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +- SP 800-63A *Enrollment and Identity Proofing* - Addresses how applicants can prove their identities and become enrolled as valid subjects within an identity system. It provides a guideline for proc
a guideline -> requirements

2017-01-20 21:40 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    provides a guideline for the assessment of the implemented system
a guideline -> requirements/recommendations.

2017-01-20 21:40 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +- SP 800-63C *Federation and Assertions* - Provides a guideline on the use of federated identity architectures and assertions to convey the results of authentication processes and relevant identity i
a guideline -> requirements

2017-01-20 21:40 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    800-37, Revision 1 [[SP 800-37]](#SP800-37) provides a guideline on
guideline -> requirements/recommendation

2017-01-20 21:40 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    assessment guideline specified in SP 800-53A [[SP
guideline -> requirements/recommendation

2017-01-22 02:52 UTC, paul-grassi approved these changes

2017-01-22 02:52 UTC, merged