SMS updates.
usnistgov/800-63-3 pull request #492
Opened 2017-01-25 18:00 UTC by pgrassi-nist

2017-01-26 04:57 UTC, jimfenton requested changes
Most serious issue is the inconsistency about whether use of a secure channel and unique identification of the device is a SHOULD or a SHALL.

2017-01-26 04:57 UTC, jimfenton commented on sp800-63b/sec5_authenticators.md
> +The out-of-band device SHALL be uniquely addressable and communication over the secondary channel SHALL be private. Some voice-over-IP telephone services can deliver text messages and voice calls wit
The first sentence requires unique addressability and private communication, but at the end of the paragraph this is only a SHOULD. These need to be consistent (and apparently weren't in the original version either, oops).

I really think we need to call out email as being unacceptable here, more strongly than PSTN. I can't think of an example where receipt of email proves possession of a specific device, and we need to be specific about that.

2017-01-26 04:57 UTC, jimfenton commented on sp800-63b/sec5_authenticators.md
> +If out-of-band verification is to be made using the public switched telephone network (PSTN), the verifier SHALL verify that the pre-registered telephone number being used is associated to a physical
The second sentence assumes a particular out-of-band flow, while below (2-3 paragraphs later), we describe three possible flows (added in response to a preview draft comment). At least the second of these is vulnerable to spoofing of the source of the text message from the claimant to the verifier.

2017-01-26 06:43 UTC, readnotify commented on sp800-63b/sec5_authenticators.md
> +If out-of-band verification is to be made using the public switched telephone network (PSTN), the verifier SHALL verify that the pre-registered telephone number being used is associated to a physical
Nice work!  Eradicate the ban on SMS by sneaking in changes to get rid of the ban.

Who do you work for?  Are you another one of these phone company or SMS-sending employees Jim ?

2017-01-26 06:54 UTC, readnotify commented
These changes are contrary to the SMS Deprecation direction of this standard.

They need to be re-worked to properly express the intent of the SMS Deprecation advice.

2017-01-26 18:22 UTC, pgrassi-nist commented on sp800-63b/sec5_authenticators.md
> +The out-of-band device SHALL be uniquely addressable and communication over the secondary channel SHALL be private. Some voice-over-IP telephone services can deliver text messages and voice calls wit
I made it an example in the upcoming commit.  I want to be more outcome driven here and less prescriptive.  So ANY method that does not prove possession of a device, such as email or voip, shall not be used.

2017-01-27 04:43 UTC, jimfenton approved these changes

2017-01-27 04:44 UTC, merged