800-63B copy-edit (+minor -3 edits)
usnistgov/800-63-3 pull request #494
Opened 2017-01-25 20:15 UTC by rajdinh

Pull request covers copy-edit for 63B in same style as -3. Also made some minor changes for -3 (corrected a reference and a few other small tweaks).

2017-01-25 20:42 UTC, jricher approved these changes

2017-01-25 20:46 UTC, paul-grassi requested changes

2017-01-25 20:46 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    however, NIST [[SP 800-30]](https://pages.nist.gov/800-63-3/sp800-63-3.html#SP800-30) offers a general
References in -3 should be put in the -3 references section rather than linking to another volume.

2017-01-25 20:46 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    process for risk assessment and risk mitigation, and NIST [[SP 800-37]](https://pages.nist.gov/800-63-3/sp800-63-3.html#SP800-37) Revision 1 provides recommendations on the selection and specific
see above

2017-01-25 20:46 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    user-to-agency process. NIST [[SP 800-53A]](https://pages.nist.gov/800-63-3/sp800-63-3.html#SP800-53A)
This reference doesn't need to be fully qualified if `#SP800-53A` is in the -3 references doc.

2017-01-25 20:46 UTC, pgrassi-nist commented on sp800-63-3/sec1_2_introduction.md
> +    part of a security authorization process as described in NIST [[SP 800-37]](https://pages.nist.gov/800-63-3/sp800-63-3.html#SP800-37), Revision 1.
i'm going to stop commenting on each of these.  Please make sure the above applies for all.

2017-01-26 05:24 UTC, jimfenton submitted a review, later dismissed
Most serious issue is backquotes that are likely to interfere with rendering.

2017-01-26 05:24 UTC, jimfenton commented on sp800-63c/sec10_usability.md
> +6. Do not display system generated attributes such as a pairwise pseudonymous identifier (not to be confused with system derived attribute claims, such as 'older than' derived from 'date of birth'),
The backquote (grave accent mark) following "with the default as" tells Markdown that a preformatted text block begins. This should be a simple ' (apostrophe) character.

2017-01-26 05:24 UTC, jimfenton commented on sp800-63c/sec11_examples.md
> + - `iss` - An HTTPS URL identifying the IdP that issued the assertion.
More backquote symbols here and on next several lines -- confuses Markdown.

2017-01-26 05:24 UTC, jimfenton commented on sp800-63c/sec3_definitions.md
> +A communication channel that uses approved encryption where the initiator of the connection (client) has authenticated the recipient (server). Authenticated protected channels provide confidentiality
Add reference to -63C.

2017-01-26 05:24 UTC, jimfenton commented on sp800-63c/sec4_federation.md
> +To mitigate the risk of unauthorized exposure of sensitive information (e.g., shoulder surfing), the IdP SHALL, by default, mask sensitive information displayed to the subscriber.  The IdP SHALL prov
Usability Considerations should not be capitalized because it is not being used as a title.

2017-01-26 18:33 UTC, paul-grassi approved these changes

2017-01-26 18:34 UTC, merged