Biometric section re: limiting unsuccesful atempts
usnistgov/800-63-3 pull request #496
Opened 2017-01-26 01:58 UTC by enewt

FIDO is doing something different, but even that is still in flux. That said, I would to propose an aligned approach, including the changes I just proposed to them that would make their approach a requirement for biometrics.

2017-01-26 02:16 UTC, jimfenton requested changes
A couple of clarifications needed.

2017-01-26 02:16 UTC, jimfenton commented on sp800-63b/sec5_authenticators.md
> +b) disabling the biometric user verification after the 5th (and subsequent) failed attempt and offering another factor (e.g. a different biometric or a PIN/Passcode if it is not already a required fa
Does "different biometric" mean a different sensor, different biometric modality, or perhaps just a different finger?

2017-01-26 02:16 UTC, jimfenton commented on sp800-63b/sec5_authenticators.md
> +a) an exponential increase of this delay, e.g. 1 minute after the 6th+ false attempt, 2 minutes after the 7th+ false attempt, 4 minutes after the 8th+, etc.
What is "this" delay (I.e., what is the initial value)? In your example, you used 1 minute, which seems like a reasonable value. Hopefully the base of the exponential increase is not 1.001 or something like that.

2017-01-26 20:27 UTC, paul-grassi approved these changes
Fenton has the right comments, so approving so I can get out of the way of the merge.

2017-01-26 20:44 UTC, enewt commented on sp800-63b/sec5_authenticators.md
> +a) an exponential increase of this delay, e.g. 1 minute after the 6th+ false attempt, 2 minutes after the 7th+ false attempt, 4 minutes after the 8th+, etc.
Copy and paste error. It's referring to a 30 second delay after 5 failed attempts.

2017-01-26 20:45 UTC, enewt commented on sp800-63b/sec5_authenticators.md
> +b) disabling the biometric user verification after the 5th (and subsequent) failed attempt and offering another factor (e.g. a different biometric or a PIN/Passcode if it is not already a required fa
I was thinking different modality. Now that you raise it, I recommend that, but it is debateable. I'd be fine with either clarification. Wdyt?

2017-01-27 04:18 UTC, jimfenton approved these changes

2017-01-27 04:18 UTC, merged