Kerberos modernize
usnistgov/800-63-3 pull request #563
Opened 2017-02-22 18:48 UTC by frozencemetery

Hello again, this is the followup to #488 (this time based on the post-public-comment branch).  It only talks about FAST, and I've moved the Kerberos definition as requested in previous review.

If SPAKE is approved by IETF within the year (since an implementation exists now), is there a mechanism by which it could be mentioned in this document, or is that too far out?

Thanks!

2017-02-23 00:27 UTC, jimfenton commented
There really isn't a mechanism to make an out-of-cycle revision for something like this. But it's not necessary; the SP 800-63-3 suite is primarily a requirements document: while in some cases it gives examples of how particular protocols (such as Kerberos) may be used, it does not prescribe the use of particular protocols. Even though SPAKE is not mentioned, it may be used as appropriate.

2017-02-23 14:05 UTC, frozencemetery commented
Okay, thanks!

2017-05-15 15:48 UTC, jricher requested changes

2017-05-15 15:48 UTC, jricher commented on sp800-63c/sec3_definitions.md
> +
This needs to get moved to the new definitions section.

2017-05-15 15:57 UTC, jricher approved these changes

2017-05-15 16:49 UTC, frozencemetery commented
@jricher do you still want changes from me, or did you take care of it?  Thanks!

2017-05-15 18:18 UTC, jricher commented
@frozencemetery I took care of it in fa22348 -- it was just putting the changes to the definition in the right file.

2017-05-16 17:47 UTC, merged